version: "3.3"

services:
  ejercicio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: machi
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
